### ISSUE TITLE
Linux 

### ISSUE THREAD

**Issue by namiagin** [bstnbuck/ItsSoEasy#1]
@bstnbuck  to run ransomware on Linux, I need to use the C99 version?

**Comment by bstnbuck** [comment]
Yes exactly. For Go and Python version use the same commands as in Windows.

As you can read in the `README` file, gcc-10.2.1 (Debian, Ubuntu, ...) or equivalent is sufficient. For compiling the following command on the commandline is sufficient:
`gcc main.c src/b64.h src/b64.c src/helper.h src/helper.c -lcrypto -lssl -Wall -o itssoeasy_client_linux`

Btw, I will probably not maintain or optimize the C code anymore.
