### ISSUE TITLE
Certs 

### ISSUE THREAD

**Issue by namiagin** [bstnbuck/ItsSoEasy#2]
In the server, the ReadMe file says "Create cert and key for TLS connection". 
In the script it is looking for 'certs/cert.pem', 'certs/key.pem. 
Do I need to create the cert files by myself? If yes, can we create them using 'let's encrypt'? 
When I run the server script I get an error that the file wasn't found.

**Comment by bstnbuck** [comment]
Yes, you can use any TLS certificate pair. With `openssl` this can be done very fast. Rename the public and private key accordingly or use a different name/path in the server script.
